# Generated by Django 5.2.17 on 2026-08-19 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_id', models.CharField(max_length=128)),
                ('catalog_file_id', models.CharField(blank=True, default='', max_length=128)),
                ('storage_used_bytes', models.BigIntegerField(blank=True, null=True)),
                ('storage_total_bytes', models.BigIntegerField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drive_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
